name: Run Tests and Collect Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Extract coverage result (Cobertura)
        run: |
          mkdir -p coverage
          find . -name 'coverage.cobertura.xml' -exec cp {} coverage/ \;

      - name: Print coverage file summary
        run: |
          echo "Generated files:"
          ls -l coverage
          
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
          
      - name: Extract coverage percentage
        run: |
          xml_file=$(find . -name 'coverage.cobertura.xml' | head -n 1)
          if [ -z "$xml_file" ]; then
            echo "❌ Error: coverage.cobertura.xml file not found."
            exit 1
          fi
          echo "Parsing coverage file: $xml_file"
          line_rate=$(xmllint --xpath 'string(/coverage/@line-rate)' "$xml_file")
          percent=$(awk "BEGIN { printf \"%.2f\", $line_rate * 100 }")
          echo "Coverage: $percent%"
          echo "COVERAGE=$percent" >> $GITHUB_ENV

      - name: Fail if coverage is below threshold
        run: |
          threshold=30
          coverage=$(echo "$COVERAGE" | cut -d'.' -f1) # integer part
          if [ "$coverage" -lt "$threshold" ]; then
            echo "❌ Coverage ($COVERAGE%) is below threshold ($threshold%)"
            exit 1
          else
            echo "✅ Coverage is sufficient: $COVERAGE%"
          fi